security:
  # Hiérarchie des rôles
  role_hierarchy:
    ROLE_ADMIN: ROLE_USER # Un admin hérite automatiquement des droits USER

  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

  providers:
    app_user_provider:
      entity:
        class: App\Entity\Participant
        property: email

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      lazy: true
      provider: app_user_provider
      form_login:
        login_path: app_login
        check_path: app_login
        username_parameter: email
        password_parameter: password
        enable_csrf: true
      logout:
        path: app_logout
        target: home  # Redirige vers la page d'accueil après logout

      remember_me:
        secret: '%kernel.secret%'
        lifetime: 604800
        path: /
        always_remember_me: false

  # ACTIVE LES ACCESS CONTROL
  access_control:
    # Routes admin uniquement
    - { path: ^/admin, roles: ROLE_ADMIN }
    # Routes pour utilisateurs connectés
    - { path: ^/sortie/create, roles: ROLE_USER }
    - { path: ^/profil/**, roles: ROLE_USER }

when@test:
  security:
    password_hashers:
      Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
        algorithm: auto
        cost: 4
        time_cost: 3
        memory_cost: 10